<a href="https://colab.research.google.com/github/ThiagoLozano/Alura_Python_para_DataScience/blob/main/02_Introducao_a_Linguagem_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <font color=yellow> PYTHON PARA DATA SCIENCE - Introdução a Linguagem Numpy
---

# <font color=yellow> 1. Ambiente do Cientista de Dados
---

# 1.1 Média de Km por Ano

In [ ]:
import numpy as np

km = np.loadtxt("carros-km.txt")
anos = np.loadtxt("carros-anos.txt", dtype=int

km_media = km / (2019 - anos)

print(km_media)

[2.77562500e+03 2.04000000e+02 1.28010345e+03            nan
 1.98130769e+03 1.53257143e+03            nan 7.75990000e+03
 1.10218889e+04 4.74725000e+03 7.56411765e+02 6.71000000e+02
 4.98738889e+03            nan 4.14570000e+03 3.85356667e+04
 6.63557143e+03            nan 1.23620000e+04 7.58650000e+03
 5.95252941e+03            nan 3.92316000e+03 3.67710714e+03
            nan            nan 1.93166667e+03            nan
 3.46164706e+03 3.37075000e+03 1.37104545e+03 2.22216667e+03
 1.77200000e+04 1.20742857e+03 1.81368000e+04 1.83229167e+03
            nan            nan 5.52600000e+02            nan
 1.55691667e+04 2.54762500e+03            nan 5.07658824e+03
            nan 5.73823529e+02 4.66300000e+03 1.33055556e+02
            nan 5.02181250e+03 8.55540000e+03 3.88430769e+03
 3.56400000e+03 7.22669231e+03 3.92722222e+03 3.24028000e+03
 9.95941667e+03            nan            nan            nan
            nan            nan 5.94475000e+04 6.06362500e+03
 5.60622222e+03 4.158652

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: RuntimeWarning: invalid value encountered in true_divide
  import sys


# 1.2 Tipo do Array Numpy

In [ ]:
print(type(km_media))

<class 'numpy.ndarray'>


# <font color=yellow> 2. Características do Python
---

# 2.1 Operaçãoes Matemáticas

### Soma

In [ ]:
2 + 2

4

### Subtração

In [ ]:
2 - 2 

0

### Multiplicação

In [ ]:
2 * 3

6

### Divisão

In [ ]:
10 / 3

3.3333333333333335

### Parte Inteira da Divisão

In [ ]:
10 // 3

3

### Exponenciação

In [ ]:
2 ** 3

8

### Resto da Divisão

In [ ]:
10 % 3

1

# 2.2 Expressões Matemáticas

In [ ]:
5 * 2 + 3 * 2

16

In [ ]:
(5 * 2) + (3 * 2)

16

In [ ]:
5 * (2 + 3) * 2

50

# 2.3 Variável _

In [ ]:
5 * 2       

In [ ]:
# _ Retorna o último valor registrado na memória
_ + 3 * 2

# 2.4 Entendendo Variáveis

In [ ]:
ano_atual = 2021

In [ ]:
ano_fabricacao = 2003

In [ ]:
km_total = 44410.0

In [ ]:
km_media = km_total / (ano_atual - ano_fabricacao)

In [ ]:
print(km_media)

2467.222222222222


# 2.5 Declaração Múltipla

In [ ]:
ano_atual, ano_fabricacao, km_total = 2021, 2003, 44410.0

In [ ]:
print(ano_atual, ano_fabricacao, km_total)

2021 2003 44410.0


# 2.6 Tipos de Dados

### Int

In [ ]:
1

1

In [ ]:
2

2

In [ ]:
3

3

In [ ]:
100

100

In [ ]:
345

345

### Float

In [ ]:
10.0

10.0

In [ ]:
5.45

5.45

In [ ]:
456.789

456.789

In [ ]:
0.4567

0.4567

In [ ]:
12.5

12.5

### Booleano

In [ ]:
True

True

In [ ]:
False

False

### Str

In [ ]:
"Python"

'Python'

In [ ]:
"Thiago"

'Thiago'

In [ ]:
"Teste"

'Teste'

In [ ]:
"Curso Alura"

'Curso Alura'

In [ ]:
"Isso é uma String"

'Isso é uma String'

### None

In [ ]:
None

# 2.7 Conversão de Tipos

In [ ]:
a = 10

In [ ]:
b = 20

In [ ]:
c = "Python é "

In [ ]:
d = "Legal"

In [ ]:
print(a + b)
print(c + d)
print(c + str(a))
print(float(b))

30
Python é Legal
Python é 10
20.0


# 2.8 Identação

In [ ]:
ano_atual = 2020

In [ ]:
ano_fabricacao = 2019

In [ ]:
if ano_atual == ano_fabricacao:
  print("Verdadeiro")
else:
  print("Falso")

# 2.9 Comentários

In [ ]:
# Isso é um comentário

In [ ]:
'''
Isso é um comentário
'''

'\nIsso é um comentário\n'

In [ ]:
"""
Isso é um comentário
"""

'\nIsso é um comentário\n'

In [ ]:
'''
isso
é
um comentário
'''

'\nisso\né\num comentário\n'

# 2.1.0 Formatação de Strings

In [ ]:
print("Olá {}!".format('Thiago'))

Olá Thiago!


In [ ]:
print("Olá {}! Este é seu acesso de número {}".format("Thiago",32))

Olá Thiago! Este é seu acesso de número 32


In [ ]:
print("Olá {nome}! Este é seu acesso de número {acessos}".format(nome="Thiago",acessos=32))

Olá Thiago! Este é seu acesso de número 32


In [ ]:
nome = "Thiago"
acessos = 21

In [ ]:
print(f"Olá {nome}! Este é seu acesso de número {acessos}")

Olá Thiago! Este é seu acesso de número 21


# <font color=yellow> 3. Trabalhando com Listas
---

# 3.1 Criando Listas

In [ ]:
acessorios = ["Rodas de Liga", "Travas Eletricas", "Piloto Automático", "Bancos de Couro", "Ar Condicionado", "Sensor de Estacionamento", "Sensor Crepuscular", "Sensor de Chuva"]

In [ ]:
print(acessorios)
print(type(acessorios))

['Rodas de Liga', 'Travas Eletricas', 'Piloto Automático', 'Bancos de Couro', 'Ar Condicionado', 'Sensor de Estacionamento', 'Sensor Crepuscular', 'Sensor de Chuva']
<class 'list'>


In [ ]:
carro_1 = ["Jetta Variant", "Motor 4.0 Turbo", 2013, 44410.0, False, ["Rodas de Liga", "Travas Elétricas", "Piloto Automático"], 88078.64]
carro_2 = ["Passat", "Motor Diesel", 1991, 5712.0, False, ["Central Múltimídia", "Teto Panrâmeco", "Freios ABS"], 106161.94]
carros = [carro_1, carro_2]

In [ ]:
print(carro_1)
print(carro_2)
print(carros)

['Jetta Variant', 'Motor 4.0 Turbo', 2013, 44410.0, False, ['Rodas de Liga', 'Travas Elétricas', 'Piloto Automático'], 88078.64]
['Passat', 'Motor Diesel', 1991, 5712.0, False, ['Central Múltimídia', 'Teto Panrâmeco', 'Freios ABS'], 106161.94]
[['Jetta Variant', 'Motor 4.0 Turbo', 2013, 44410.0, False, ['Rodas de Liga', 'Travas Elétricas', 'Piloto Automático'], 88078.64], ['Passat', 'Motor Diesel', 1991, 5712.0, False, ['Central Múltimídia', 'Teto Panrâmeco', 'Freios ABS'], 106161.94]]


# 3.2 Operação com Listas

### Elementos que pertencem a lista ou não

In [ ]:
print("Rodas de Liga" in acessorios)

NameError: ignored

In [ ]:
print("4 x 4" in acessorios)

NameError: ignored

In [ ]:
print("Rodas de Liga" not in acessorios)

In [ ]:
print("4 x 4" not in acessorios)

### Concatenação de Listas

In [ ]:
a = ["Rodas de Liga", "Travas Eletricas", "Piloto Automático", "Bancos de Couro", "Ar Condicionado",]

In [ ]:
b = ["Sensor de Estacionamento", "Sensor Crepuscular", "Sensor de Chuva"]

In [ ]:
print(a + b)

### Tamanho da Lista

In [ ]:
print(len(a))

# 3.4 Seleção de Listas

In [ ]:
print(acessorios[0])

Rodas de Liga


In [ ]:
print(acessorios[1])

Travas Eletricas


In [ ]:
print(acessorios[-1])

Sensor de Chuva


In [ ]:
print(carros[0])

['Jetta Variant', 'Motor 4.0 Turbo', 2013, 44410.0, False, ['Rodas de Liga', 'Travas Elétricas', 'Piloto Automático'], 88078.64]


In [ ]:
print(carros[0][0])

Jetta Variant


In [ ]:
print(carros[0][-2][1])

Travas Elétricas


In [ ]:
print(acessorios[2:5])

['Piloto Automático', 'Bancos de Couro', 'Ar Condicionado']


In [ ]:
print(acessorios[2:])

['Piloto Automático', 'Bancos de Couro', 'Ar Condicionado', 'Sensor de Estacionamento', 'Sensor Crepuscular', 'Sensor de Chuva']


In [ ]:
print(acessorios[:4])

['Rodas de Liga', 'Travas Eletricas', 'Piloto Automático', 'Bancos de Couro']


# 3.4 Métodos

### Ordena uma Lista

In [ ]:
acessorios.sort()

In [ ]:
print(acessorios)

['Ar Condicionado', 'Bancos de Couro', 'Piloto Automático', 'Rodas de Liga', 'Sensor Crepuscular', 'Sensor de Chuva', 'Sensor de Estacionamento', 'Travas Eletricas']


### Adiciona um Elemento na Lista

In [ ]:
acessorios.append("4 x 4")

In [ ]:
print(acessorios)

['Ar Condicionado', 'Bancos de Couro', 'Piloto Automático', 'Rodas de Liga', 'Sensor Crepuscular', 'Sensor de Chuva', 'Sensor de Estacionamento', 'Travas Eletricas', '4 x 4']


### Remove um Elemento da lista

In [ ]:
acessorios.pop()

'4 x 4'

In [ ]:
print(acessorios)

['Ar Condicionado', 'Bancos de Couro', 'Piloto Automático', 'Rodas de Liga', 'Sensor Crepuscular', 'Sensor de Chuva', 'Sensor de Estacionamento', 'Travas Eletricas']


In [ ]:
acessorios.pop(3)

'Rodas de Liga'

In [ ]:
print(acessorios)

['Ar Condicionado', 'Bancos de Couro', 'Piloto Automático', 'Sensor Crepuscular', 'Sensor de Chuva', 'Sensor de Estacionamento', 'Travas Eletricas']


### Copia uma lista

In [ ]:
a = [1, 2, 3, 4]

In [ ]:
b = a.copy()

In [ ]:
print(a)
print(b)

[1, 2, 3, 4]
[1, 2, 3, 4]


# <font color=yellow> 4. Condições e Laços com Listas
---

# 4.1 Loops com Listas

In [ ]:
acessorios = ["Rodas de Liga", "Travas Eletricas", "Piloto Automático", "Bancos de Couro", "Ar Condicionado", "Sensor de Estacionamento", "Sensor Crepuscular", "Sensor de Chuva"]

In [ ]:
for item in acessorios:
  print(item)

Rodas de Liga
Travas Eletricas
Piloto Automático
Bancos de Couro
Ar Condicionado
Sensor de Estacionamento
Sensor Crepuscular
Sensor de Chuva


# 4.2 List comprehensions


In [ ]:
range(10)

range(0, 10)

In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
for i in range(10):
  print(i ** 2)

0
1
4
9
16
25
36
49
64
81


In [ ]:
quadrado = []
for i in range(10):
  quadrado.append(i ** 2)
  
print(quadrado)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [ ]:
[i ** 2 for i in range(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

# 4.3 Loos Aninhados

In [ ]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]

In [ ]:
for lista in dados:
  print(lista)

['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']
['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento']
['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']


In [ ]:
for lista in dados:
  for item in lista:
    print(item)

Rodas de liga
Travas elétricas
Piloto automático
Bancos de couro
Ar condicionado
Sensor de estacionamento
Sensor crepuscular
Sensor de chuva
Central multimídia
Teto panorâmico
Freios ABS
4 X 4
Painel digital
Piloto automático
Bancos de couro
Câmera de estacionamento
Piloto automático
Controle de estabilidade
Sensor crepuscular
Freios ABS
Câmbio automático
Bancos de couro
Central multimídia
Vidros elétricos


In [ ]:
acessorios = []

for lista in dados:
  for item in lista:
    acessorios.append(item)

print(acessorios)

['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva', 'Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento', 'Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']


In [ ]:
list(set(acessorios))

['Travas elétricas',
 'Teto panorâmico',
 'Vidros elétricos',
 'Piloto automático',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Central multimídia',
 '4 X 4',
 'Sensor crepuscular',
 'Painel digital',
 'Controle de estabilidade',
 'Freios ABS',
 'Bancos de couro',
 'Rodas de liga',
 'Câmera de estacionamento',
 'Sensor de chuva',
 'Câmbio automático']

In [ ]:
[item for lista in dados for item in lista]

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Central multimídia',
 'Teto panorâmico',
 'Freios ABS',
 '4 X 4',
 'Painel digital',
 'Piloto automático',
 'Bancos de couro',
 'Câmera de estacionamento',
 'Piloto automático',
 'Controle de estabilidade',
 'Sensor crepuscular',
 'Freios ABS',
 'Câmbio automático',
 'Bancos de couro',
 'Central multimídia',
 'Vidros elétricos']

In [ ]:
list(set([item for lista in dados for item in lista]))

['Travas elétricas',
 'Teto panorâmico',
 'Vidros elétricos',
 'Piloto automático',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Central multimídia',
 '4 X 4',
 'Sensor crepuscular',
 'Painel digital',
 'Controle de estabilidade',
 'Freios ABS',
 'Bancos de couro',
 'Rodas de liga',
 'Câmera de estacionamento',
 'Sensor de chuva',
 'Câmbio automático']

# 4.4 Instrução IF

###
 Operadores de Comparações

In [ ]:
# 1º item da lista - Nome do veículo
# 2º item da lista - Ano de fabricação
# 3º item da lista - Veículo é zero km?

dados = [
    ['Jetta Variant', 2003, False],
    ['Passat', 1991, False],
    ['Crossfox', 1990, False],
    ['DS5', 2019, True],
    ['Aston Martin DB4', 2006, False],
    ['Palio Weekend', 2012, False],
    ['A5', 2019, True],
    ['Série 3 Cabrio', 2009, False],
    ['Dodge Jorney', 2019, False],
    ['Carens', 2011, False]
]

In [ ]:
zero_km_y = []

for lista in dados:
  if lista[2] == True:
    zero_km_y.append(lista)

print(zero_km_y)

[['DS5', 2019, True], ['A5', 2019, True]]


In [ ]:
zero_km_n = []

for lista in dados:
  if lista[2] == False:
    zero_km_n.append(lista)

print(zero_km_n)

[['Jetta Variant', 2003, False], ['Passat', 1991, False], ['Crossfox', 1990, False], ['Aston Martin DB4', 2006, False], ['Palio Weekend', 2012, False], ['Série 3 Cabrio', 2009, False], ['Dodge Jorney', 2019, False], ['Carens', 2011, False]]


In [ ]:
[lista for lista in dados if lista[2] == True]

[['DS5', 2019, True], ['A5', 2019, True]]

In [ ]:
[lista for lista in dados if lista[2] == False]

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

# 4.5 Instruções IF-ELSE e IF-ELIF-ELSE

In [ ]:
zero_km_y, zero_km_n  = [], []

for lista in dados:
  if lista[2] == True:
    zero_km_y.append(lista)
  else:
    zero_km_n.append(lista)

In [ ]:
print(zero_km_y)

[['DS5', 2019, True], ['A5', 2019, True]]


In [ ]:
print(zero_km_n)

[['Jetta Variant', 2003, False], ['Passat', 1991, False], ['Crossfox', 1990, False], ['Aston Martin DB4', 2006, False], ['Palio Weekend', 2012, False], ['Série 3 Cabrio', 2009, False], ['Dodge Jorney', 2019, False], ['Carens', 2011, False]]


In [ ]:
dados

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['DS5', 2019, True],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [ ]:
print('AND')
print(f'(True and True) o resultado é: {True and True}')
print(f'(True and False) o resultado é: {True and False}')
print(f'(False and True) o resultado é: {False and True}')
print(f'(False and False) o resultado é: {False and False}')

AND
(True and True) o resultado é: True
(True and False) o resultado é: False
(False and True) o resultado é: False
(False and False) o resultado é: False


In [ ]:
print('OR')
print(f'(True or True) o resultado é: {True or True}')
print(f'(True or False) o resultado é: {True or False}')
print(f'(False or True) o resultado é: {False or True}')
print(f'(False or False) o resultado é: {False or False}')

OR
(True or True) o resultado é: True
(True or False) o resultado é: True
(False or True) o resultado é: True
(False or False) o resultado é: False


In [ ]:
a, b , c = [], [], []

for lista in dados:
  if lista[1] <= 2000:
    a.append(lista)
  elif lista[1] > 2000 and lista[1] <= 2010:
    b.append(lista)
  else:
    c.append(lista)

In [ ]:
print(a)

[['Passat', 1991, False], ['Crossfox', 1990, False]]


In [ ]:
print(b)

[['Jetta Variant', 2003, False], ['Aston Martin DB4', 2006, False], ['Série 3 Cabrio', 2009, False]]


In [ ]:
print(c)

[['DS5', 2019, True], ['Palio Weekend', 2012, False], ['A5', 2019, True], ['Dodge Jorney', 2019, False], ['Carens', 2011, False]]


In [ ]:
a, b , c = [], [], []

for lista in dados:
  if lista[1] <= 2000:
    a.append(lista)
  elif 2000 < lista[1] <= 2010:
    b.append(lista)
  else:
    c.append(lista)

In [ ]:
print(a)

[['Passat', 1991, False], ['Crossfox', 1990, False]]


In [ ]:
print(b)

[['Jetta Variant', 2003, False], ['Aston Martin DB4', 2006, False], ['Série 3 Cabrio', 2009, False]]


In [ ]:
print(c)

[['DS5', 2019, True], ['Palio Weekend', 2012, False], ['A5', 2019, True], ['Dodge Jorney', 2019, False], ['Carens', 2011, False]]


# <font color=yellow> 5. Numpy Básico
---
Numpy é a abreviação de Numerical Python e é um dos pacotes mais importantes para processamento numérico em Python. Numpy oferece a base para a maioria dos pacotes de aplicações científicas que utilizem dados numéricos em Python (estruturas de dados e algoritmos). Pode-se destacar os seguintes recursos que o pacote Numpy contém:

- Um poderoso objeto array multidimensional;
- Funções matemáticas sofisticadas para operações com arrays sem a necessidade de utilização de laços *for*;
- Recursos de algebra linear e geração de números aleatórios

Além de seus óbvios usos científicos, o pacote NumPy também é muito utilizado em análise de dados como um eficiente contêiner multidimensional de dados genéricos para transporte entre diversos algoritmos e bibliotecas em Python.

**Versão:** 1.16.5

**Instalação:** https://scipy.org/install.html

**Documentação:** https://numpy.org/doc/1.16/

### Pacotes

Existem diversos pacotes Python disponíveis para download na internet. Cada pacote tem como objetivo a solução de determinado tipo de problema e para isso são desenvolvidos novos tipos, funções e métodos.

Alguns pacotes são bastante utilizados em um contexto de ciência de dados como por exemplo:

- Numpy
- Pandas
- Scikit-learn
- Matplotlib

Alguns pacotes não são distribuídos com a instalação default do Python. Neste caso devemos instalar os pacotes que necessitamos em nosso sistema para podermos utilizar suas funcionalidades.

# 5.1 Importando Todo o Pacote

### Padrão

In [ ]:
import numpy

In [ ]:
numpy.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Atribuindo um Apelido

In [ ]:
import numpy as np

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Importando um Pacote Específico

In [ ]:
from numpy import arange

In [ ]:
arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 5.2 Criando um Arrays Numpy

### A partir de Listas

In [ ]:
km = np.array([1000,2300,4987,1500])

In [ ]:
km

array([1000, 2300, 4987, 1500])

In [ ]:
type(km)

numpy.ndarray

In [ ]:
km.dtype

dtype('int64')

### A partir de Dados Externos

In [ ]:
km = np.loadtxt(fname = "carros-km.txt", dtype=int)

In [ ]:
km

array([ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
        99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
        46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
            0,      0,   5795,      0,  58848,  94381,  30163,  53332,
        17720,  33808,  90684,  43975,      0,      0,   5526,      0,
        93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
            0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
       119513,      0,      0,      0,      0,      0, 118895,  48509,
       100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
        54395,  26731,  44329, 118236, 113808,    610,      0,      0,
        12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
            0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
       110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
        26544,  52596,  47503,  89056,  28834, 110564,  56638,  17357,
      

In [ ]:
km.dtype

dtype('int64')

### Arrays com Duas Dimensões

In [ ]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]

In [ ]:
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [ ]:
acessorios = np.array(dados)

In [ ]:
acessorios

array([['Rodas de liga', 'Travas elétricas', 'Piloto automático',
        'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento',
        'Sensor crepuscular', 'Sensor de chuva'],
       ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4',
        'Painel digital', 'Piloto automático', 'Bancos de couro',
        'Câmera de estacionamento'],
       ['Piloto automático', 'Controle de estabilidade',
        'Sensor crepuscular', 'Freios ABS', 'Câmbio automático',
        'Bancos de couro', 'Central multimídia', 'Vidros elétricos']],
      dtype='<U24')

In [ ]:
km.shape

(258,)

In [ ]:
acesorios.shape

(3, 8)

### Comparando Desempenho com Listas

In [ ]:
np_array = np.arange(1000000)

In [ ]:
py_list = list(range(1000000))

In [ ]:
%time for _ in range(100): np_array *= 2

CPU times: user 76.3 ms, sys: 0 ns, total: 76.3 ms
Wall time: 79.5 ms


In [ ]:
%time for _ in range(100): py_list = [x * 2 for x in py_list]

CPU times: user 7.82 s, sys: 1.67 s, total: 9.49 s
Wall time: 9.52 s


# 5.3 Operações Aritméticas com Arrys Numpy

### Operações com Arrays e Constantes

In [ ]:
km = [44410., 5712., 37123., 0., 25757.]
anos = [2003, 1991, 1990, 2019, 2006]

In [ ]:
idade = 2020 - anos

TypeError: ignored

In [ ]:
km = np.array([44410., 5712., 37123., 0., 25757.])
anos = np.array([2003, 1991, 1990, 2019, 2006])

In [ ]:
idade = 2020 - anos

In [ ]:
idade

array([17, 29, 30,  1, 14])

### Operação entre Arrays

In [ ]:
km_media = km/idade

In [ ]:
km_media

array([2612.35294118,  196.96551724, 1237.43333333,    0.        ,
       1839.78571429])

### Operações com Arrays de Duas Dimensões

In [ ]:
dados = np.array([km, anos])

In [ ]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [ ]:
dados.shape

(2, 5)

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [ ]:
dados[0]

array([44410.,  5712., 37123.,     0., 25757.])

In [ ]:
dados[1]

array([2003., 1991., 1990., 2019., 2006.])

In [ ]:
km_media = dados[0]/(2020 - dados[1])

In [ ]:
km_media

array([2612.35294118,  196.96551724, 1237.43333333,    0.        ,
       1839.78571429])

# 5.4 Seleções com Arrays

In [ ]:
dados 

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

### Indexação

In [ ]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
contador[0]

0

In [ ]:
itens = 6
index = itens - 1
contador[index]

5

In [ ]:
contador[-1]

9

In [ ]:
dados[0]

array([44410.,  5712., 37123.,     0., 25757.])

In [ ]:
dados[1]

array([2003., 1991., 1990., 2019., 2006.])

In [ ]:
dados[1][2]

1990.0

In [ ]:
dados[1,2]

1990.0

### Fatiamento

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [ ]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
contador[1:4]

array([1, 2, 3])

In [ ]:
contador[1:8:2]

array([1, 3, 5, 7])

In [ ]:
contador[::2]

array([0, 2, 4, 6, 8])

In [ ]:
contador[1::2]

array([1, 3, 5, 7, 9])

In [ ]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [ ]:
dados[:, 1:4]

array([[ 5712., 37123.,     0.],
       [ 1991.,  1990.,  2019.]])

In [ ]:
dados[:, 1:3]

array([[ 5712., 37123.],
       [ 1991.,  1990.]])

In [ ]:
dados[:, 1:3][0] / (2020 - dados[:, 1:3][1])

array([ 196.96551724, 1237.43333333])

### Indexção com Arrays Booleano

In [ ]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
contador > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [ ]:
contador[contador > 5]

array([6, 7, 8, 9])

In [ ]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [ ]:
dados[1] > 2000

array([ True, False, False,  True,  True])

In [ ]:
dados[:, dados[1] > 2000]

array([[44410.,     0., 25757.],
       [ 2003.,  2019.,  2006.]])

In [ ]:
dados[:, dados[1] > 2000] / (2020 - dados[:, dados[1] > 2000][1])

array([[2612.35294118,    0.        , 1839.78571429],
       [ 117.82352941, 2019.        ,  143.28571429]])

# 5.5 Atributos e Métodos com Numpy

In [ ]:
dados = np.array([[44410., 5712., 37123., 0., 25757.],
                  [2003, 1991, 1990, 2019, 2006]])
dados

NameError: ignored

## ndarray.shape

Retorna uma tupla com as dimensões do array.


In [ ]:
dados.shape

NameError: ignored

## *ndarray.ndim*

Retorna o número de dimensões do array.

In [ ]:
dados.ndim

## *ndarray.size*

Retorna o número de elementos do array.

In [ ]:
dados.size

### *ndarray.dtype*

Retorna o tipo de dados dos elementos do array.

In [ ]:
dados.dtype

## *ndarray.T*

Retorna o array transposto, isto é, converte linhas em colunas e vice versa.

In [ ]:
dados.T

## *ndarray.tolist()*

Retorna o array como uma lista Python.

In [ ]:
dados.tolist()

## *ndarray.reshape(shape[, order])*

Retorna um array que contém os mesmos dados com uma nova forma.

In [ ]:
contador = np.arange(10)
contador

In [ ]:
contador.reshape((5,2))

In [ ]:
contador.reshape((5,2), order='C')

In [ ]:
contador.reshape((5,2), order='F')

In [ ]:
km = [44410, 5712, 37123, 0, 25757]
anos = [2003, 1991, 1990, 2019, 2006]

In [ ]:
info_carros = km + anos
info_carros

In [ ]:
np.array(info_carros)

In [ ]:
np.array(info_carros).reshape((2,5))

In [ ]:
np.array(info_carros).reshape((5,2), order='F')

## *ndarray.resize(new_shape[, refcheck])*

Altera a forma e o tamanho do array.

In [ ]:
dados_new = dados.copy()
dados_new

In [ ]:
dados_new.resize((3,5),refcheck=False)

In [ ]:
dados_new

In [ ]:
dados_new[2] = dados_new[0] / (2021 - dados_new[1])

In [ ]:
dados_new

# 5.6 Estatísticas com Array Numpy

In [ ]:
anos = np.loadtxt(fname = "carros-anos.txt", dtype = int)
km = np.loadtxt(fname = "carros-km.txt")
valor = np.loadtxt(fname = "carros-valor.txt")

In [ ]:
anos.shape

(258,)

In [ ]:
dataset = np.column_stack((anos, km, valor))

In [ ]:
dataset

In [ ]:
dataset.shape

(258, 3)

## *np.mean()*

Retorna a média dos elementos do array ao longo do eixo especificado.

In [ ]:
np.mean(dataset, axis = 0)

array([ 2007.51162791, 44499.41472868, 98960.51310078])

In [ ]:
np.mean(dataset[:, 1])

44499.41472868217

In [ ]:
np.mean(dataset[:, 2])

98960.51310077519

# <font color=yellow> 6. Ambiente do Cientista de Dados
---

# 6.1 Média de Km por Ano

In [ ]:
import numpy as np

km = np.loadtxt("carros-km.txt")
anos = np.loadtxt("carros-anos.txt", dtype=int

km_media = km / (2019 - anos)

print(km_media)

[2.77562500e+03 2.04000000e+02 1.28010345e+03            nan
 1.98130769e+03 1.53257143e+03            nan 7.75990000e+03
 1.10218889e+04 4.74725000e+03 7.56411765e+02 6.71000000e+02
 4.98738889e+03            nan 4.14570000e+03 3.85356667e+04
 6.63557143e+03            nan 1.23620000e+04 7.58650000e+03
 5.95252941e+03            nan 3.92316000e+03 3.67710714e+03
            nan            nan 1.93166667e+03            nan
 3.46164706e+03 3.37075000e+03 1.37104545e+03 2.22216667e+03
 1.77200000e+04 1.20742857e+03 1.81368000e+04 1.83229167e+03
            nan            nan 5.52600000e+02            nan
 1.55691667e+04 2.54762500e+03            nan 5.07658824e+03
            nan 5.73823529e+02 4.66300000e+03 1.33055556e+02
            nan 5.02181250e+03 8.55540000e+03 3.88430769e+03
 3.56400000e+03 7.22669231e+03 3.92722222e+03 3.24028000e+03
 9.95941667e+03            nan            nan            nan
            nan            nan 5.94475000e+04 6.06362500e+03
 5.60622222e+03 4.158652

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: RuntimeWarning: invalid value encountered in true_divide
  import sys


# 6.2 Tipo do Array Numpy

In [ ]:
print(type(km_media))

<class 'numpy.ndarray'>


# <font color=yellow> 7. Características do Python
---

# 7.1 Operaçãoes Matemáticas

### Soma

In [ ]:
2 + 2

4

### Subtração

In [ ]:
2 - 2 

0

### Multiplicação

In [ ]:
2 * 3

6

### Divisão

In [ ]:
10 / 3

3.3333333333333335

### Parte Inteira da Divisão

In [ ]:
10 // 3

3

### Exponenciação

In [ ]:
2 ** 3

8

### Resto da Divisão

In [ ]:
10 % 3

1

# 7.2 Expressões Matemáticas

In [ ]:
5 * 2 + 3 * 2

16

In [ ]:
(5 * 2) + (3 * 2)

16

In [ ]:
5 * (2 + 3) * 2

50

# 7.3 Variável _

In [ ]:
5 * 2       

In [ ]:
# _ Retorna o último valor registrado na memória
_ + 3 * 2

# 7.4 Entendendo Variáveis

In [ ]:
ano_atual = 2021

In [ ]:
ano_fabricacao = 2003

In [ ]:
km_total = 44410.0

In [ ]:
km_media = km_total / (ano_atual - ano_fabricacao)

In [ ]:
print(km_media)

2467.222222222222


# 7.5 Declaração Múltipla

In [ ]:
ano_atual, ano_fabricacao, km_total = 2021, 2003, 44410.0

In [ ]:
print(ano_atual, ano_fabricacao, km_total)

2021 2003 44410.0


# 7.6 Tipos de Dados

### Int

In [ ]:
1

1

In [ ]:
2

2

In [ ]:
3

3

In [ ]:
100

100

In [ ]:
345

345

### Float

In [ ]:
10.0

10.0

In [ ]:
5.45

5.45

In [ ]:
456.789

456.789

In [ ]:
0.4567

0.4567

In [ ]:
12.5

12.5

### Booleano

In [ ]:
True

True

In [ ]:
False

False

### Str

In [ ]:
"Python"

'Python'

In [ ]:
"Thiago"

'Thiago'

In [ ]:
"Teste"

'Teste'

In [ ]:
"Curso Alura"

'Curso Alura'

In [ ]:
"Isso é uma String"

'Isso é uma String'

### None

In [ ]:
None

# 7.7 Conversão de Tipos

In [ ]:
a = 10

In [ ]:
b = 20

In [ ]:
c = "Python é "

In [ ]:
d = "Legal"

In [ ]:
print(a + b)
print(c + d)
print(c + str(a))
print(float(b))

30
Python é Legal
Python é 10
20.0


# 7.8 Identação

In [ ]:
ano_atual = 2020

In [ ]:
ano_fabricacao = 2019

In [ ]:
if ano_atual == ano_fabricacao:
  print("Verdadeiro")
else:
  print("Falso")

# 7.9 Comentários

In [ ]:
# Isso é um comentário

In [ ]:
'''
Isso é um comentário
'''

In [ ]:
"""
Isso é um comentário
"""

In [ ]:
'''
isso
é
um comentário
'''

# 7.1.0 Formatação de Strings

In [ ]:
print("Olá {}!".format('Thiago'))

Olá Thiago!


In [ ]:
print("Olá {}! Este é seu acesso de número {}".format("Thiago",32))

Olá Thiago! Este é seu acesso de número 32


In [ ]:
print("Olá {nome}! Este é seu acesso de número {acessos}".format(nome="Thiago",acessos=32))

Olá Thiago! Este é seu acesso de número 32


In [ ]:
nome = "Thiago"
acessos = 21

In [ ]:
print(f"Olá {nome}! Este é seu acesso de número {acessos}")

Olá Thiago! Este é seu acesso de número 21


# <font color=yellow> 8. Trabalhando com Listas
---

# 8.1 Criando Listas

In [ ]:
acessorios = ["Rodas de Liga", "Travas Eletricas", "Piloto Automático", "Bancos de Couro", "Ar Condicionado", "Sensor de Estacionamento", "Sensor Crepuscular", "Sensor de Chuva"]

In [ ]:
print(acessorios)
print(type(acessorios))

['Rodas de Liga', 'Travas Eletricas', 'Piloto Automático', 'Bancos de Couro', 'Ar Condicionado', 'Sensor de Estacionamento', 'Sensor Crepuscular', 'Sensor de Chuva']
<class 'list'>


In [ ]:
carro_1 = ["Jetta Variant", "Motor 4.0 Turbo", 2013, 44410.0, False, ["Rodas de Liga", "Travas Elétricas", "Piloto Automático"], 88078.64]
carro_2 = ["Passat", "Motor Diesel", 1991, 5712.0, False, ["Central Múltimídia", "Teto Panrâmeco", "Freios ABS"], 106161.94]
carros = [carro_1, carro_2]

In [ ]:
print(carro_1)
print(carro_2)
print(carros)

['Jetta Variant', 'Motor 4.0 Turbo', 2013, 44410.0, False, ['Rodas de Liga', 'Travas Elétricas', 'Piloto Automático'], 88078.64]
['Passat', 'Motor Diesel', 1991, 5712.0, False, ['Central Múltimídia', 'Teto Panrâmeco', 'Freios ABS'], 106161.94]
[['Jetta Variant', 'Motor 4.0 Turbo', 2013, 44410.0, False, ['Rodas de Liga', 'Travas Elétricas', 'Piloto Automático'], 88078.64], ['Passat', 'Motor Diesel', 1991, 5712.0, False, ['Central Múltimídia', 'Teto Panrâmeco', 'Freios ABS'], 106161.94]]


# 8.2 Operação com Listas

### Elementos que pertencem a lista ou não

In [ ]:
print("Rodas de Liga" in acessorios)

In [ ]:
print("4 x 4" in acessorios)

In [ ]:
print("Rodas de Liga" not in acessorios)

In [ ]:
print("4 x 4" not in acessorios)

### Concatenação de Listas

In [ ]:
a = ["Rodas de Liga", "Travas Eletricas", "Piloto Automático", "Bancos de Couro", "Ar Condicionado",]

In [ ]:
b = ["Sensor de Estacionamento", "Sensor Crepuscular", "Sensor de Chuva"]

In [ ]:
print(a + b)

['Rodas de Liga', 'Travas Eletricas', 'Piloto Automático', 'Bancos de Couro', 'Ar Condicionado', 'Sensor de Estacionamento', 'Sensor Crepuscular', 'Sensor de Chuva']


### Tamanho da Lista

In [ ]:
print(len(a))

5


# 8.3 Seleção de Listas

In [ ]:
print(acessorios[0])

Rodas de Liga


In [ ]:
print(acessorios[1])

Travas Eletricas


In [ ]:
print(acessorios[-1])

Sensor de Chuva


In [ ]:
print(carros[0])

['Jetta Variant', 'Motor 4.0 Turbo', 2013, 44410.0, False, ['Rodas de Liga', 'Travas Elétricas', 'Piloto Automático'], 88078.64]


In [ ]:
print(carros[0][0])

Jetta Variant


In [ ]:
print(carros[0][-2][1])

Travas Elétricas


In [ ]:
print(acessorios[2:5])

['Piloto Automático', 'Bancos de Couro', 'Ar Condicionado']


In [ ]:
print(acessorios[2:])

['Piloto Automático', 'Bancos de Couro', 'Ar Condicionado', 'Sensor de Estacionamento', 'Sensor Crepuscular', 'Sensor de Chuva']


In [ ]:
print(acessorios[:4])

['Rodas de Liga', 'Travas Eletricas', 'Piloto Automático', 'Bancos de Couro']


# 8.4 Métodos

### Ordena uma Lista

In [ ]:
acessorios.sort()

In [ ]:
print(acessorios)

['Ar Condicionado', 'Bancos de Couro', 'Piloto Automático', 'Rodas de Liga', 'Sensor Crepuscular', 'Sensor de Chuva', 'Sensor de Estacionamento', 'Travas Eletricas']


### Adiciona um Elemento na Lista

In [ ]:
acessorios.append("4 x 4")

In [ ]:
print(acessorios)

['Ar Condicionado', 'Bancos de Couro', 'Piloto Automático', 'Rodas de Liga', 'Sensor Crepuscular', 'Sensor de Chuva', 'Sensor de Estacionamento', 'Travas Eletricas', '4 x 4']


### Remove um Elemento da lista

In [ ]:
acessorios.pop()

'4 x 4'

In [ ]:
print(acessorios)

['Ar Condicionado', 'Bancos de Couro', 'Piloto Automático', 'Rodas de Liga', 'Sensor Crepuscular', 'Sensor de Chuva', 'Sensor de Estacionamento', 'Travas Eletricas']


In [ ]:
acessorios.pop(3)

'Rodas de Liga'

In [ ]:
print(acessorios)

['Ar Condicionado', 'Bancos de Couro', 'Piloto Automático', 'Sensor Crepuscular', 'Sensor de Chuva', 'Sensor de Estacionamento', 'Travas Eletricas']


### Copia uma lista

In [ ]:
a = [1, 2, 3, 4]

In [ ]:
b = a.copy()

In [ ]:
print(a)
print(b)

[1, 2, 3, 4]
[1, 2, 3, 4]


# <font color=yellow> 9. Condições e Laços com Listas
---

# 9.1 Loops com Listas

In [ ]:
acessorios = ["Rodas de Liga", "Travas Eletricas", "Piloto Automático", "Bancos de Couro", "Ar Condicionado", "Sensor de Estacionamento", "Sensor Crepuscular", "Sensor de Chuva"]

In [ ]:
for item in acessorios:
  print(item)

Rodas de Liga
Travas Eletricas
Piloto Automático
Bancos de Couro
Ar Condicionado
Sensor de Estacionamento
Sensor Crepuscular
Sensor de Chuva


# 9.2 List comprehensions


In [ ]:
range(10)

range(0, 10)

In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
for i in range(10):
  print(i ** 2)

0
1
4
9
16
25
36
49
64
81


In [ ]:
quadrado = []
for i in range(10):
  quadrado.append(i ** 2)
  
print(quadrado)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [ ]:
[i ** 2 for i in range(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

# 9.3 Loos Aninhados

In [ ]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]

In [ ]:
for lista in dados:
  print(lista)

['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']
['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento']
['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']


In [ ]:
for lista in dados:
  for item in lista:
    print(item)

Rodas de liga
Travas elétricas
Piloto automático
Bancos de couro
Ar condicionado
Sensor de estacionamento
Sensor crepuscular
Sensor de chuva
Central multimídia
Teto panorâmico
Freios ABS
4 X 4
Painel digital
Piloto automático
Bancos de couro
Câmera de estacionamento
Piloto automático
Controle de estabilidade
Sensor crepuscular
Freios ABS
Câmbio automático
Bancos de couro
Central multimídia
Vidros elétricos


In [ ]:
acessorios = []

for lista in dados:
  for item in lista:
    acessorios.append(item)

print(acessorios)

['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva', 'Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento', 'Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']


In [ ]:
list(set(acessorios))

['Sensor crepuscular',
 'Teto panorâmico',
 'Painel digital',
 'Piloto automático',
 'Freios ABS',
 'Travas elétricas',
 'Rodas de liga',
 'Vidros elétricos',
 'Câmera de estacionamento',
 'Bancos de couro',
 'Ar condicionado',
 'Central multimídia',
 'Sensor de estacionamento',
 'Câmbio automático',
 '4 X 4',
 'Sensor de chuva',
 'Controle de estabilidade']

In [ ]:
[item for lista in dados for item in lista]

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Central multimídia',
 'Teto panorâmico',
 'Freios ABS',
 '4 X 4',
 'Painel digital',
 'Piloto automático',
 'Bancos de couro',
 'Câmera de estacionamento',
 'Piloto automático',
 'Controle de estabilidade',
 'Sensor crepuscular',
 'Freios ABS',
 'Câmbio automático',
 'Bancos de couro',
 'Central multimídia',
 'Vidros elétricos']

In [ ]:
list(set([item for lista in dados for item in lista]))

['Sensor crepuscular',
 'Teto panorâmico',
 'Painel digital',
 'Piloto automático',
 'Freios ABS',
 'Travas elétricas',
 'Rodas de liga',
 'Vidros elétricos',
 'Câmera de estacionamento',
 'Bancos de couro',
 'Ar condicionado',
 'Central multimídia',
 'Sensor de estacionamento',
 'Câmbio automático',
 '4 X 4',
 'Sensor de chuva',
 'Controle de estabilidade']

# 9.4 Instrução IF

###
 Operadores de Comparações

In [ ]:
# 1º item da lista - Nome do veículo
# 2º item da lista - Ano de fabricação
# 3º item da lista - Veículo é zero km?

dados = [
    ['Jetta Variant', 2003, False],
    ['Passat', 1991, False],
    ['Crossfox', 1990, False],
    ['DS5', 2019, True],
    ['Aston Martin DB4', 2006, False],
    ['Palio Weekend', 2012, False],
    ['A5', 2019, True],
    ['Série 3 Cabrio', 2009, False],
    ['Dodge Jorney', 2019, False],
    ['Carens', 2011, False]
]

In [ ]:
zero_km_y = []

for lista in dados:
  if lista[2] == True:
    zero_km_y.append(lista)

print(zero_km_y)

[['DS5', 2019, True], ['A5', 2019, True]]


In [ ]:
zero_km_n = []

for lista in dados:
  if lista[2] == False:
    zero_km_n.append(lista)

print(zero_km_n)

[['Jetta Variant', 2003, False], ['Passat', 1991, False], ['Crossfox', 1990, False], ['Aston Martin DB4', 2006, False], ['Palio Weekend', 2012, False], ['Série 3 Cabrio', 2009, False], ['Dodge Jorney', 2019, False], ['Carens', 2011, False]]


In [ ]:
[lista for lista in dados if lista[2] == True]

[['DS5', 2019, True], ['A5', 2019, True]]

In [ ]:
[lista for lista in dados if lista[2] == False]

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

# 9.5 Instruções IF-ELSE e IF-ELIF-ELSE

In [ ]:
zero_km_y, zero_km_n  = [], []

for lista in dados:
  if lista[2] == True:
    zero_km_y.append(lista)
  else:
    zero_km_n.append(lista)

In [ ]:
print(zero_km_y)

[['DS5', 2019, True], ['A5', 2019, True]]


In [ ]:
print(zero_km_n)

[['Jetta Variant', 2003, False], ['Passat', 1991, False], ['Crossfox', 1990, False], ['Aston Martin DB4', 2006, False], ['Palio Weekend', 2012, False], ['Série 3 Cabrio', 2009, False], ['Dodge Jorney', 2019, False], ['Carens', 2011, False]]


In [ ]:
dados

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['DS5', 2019, True],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [ ]:
print('AND')
print(f'(True and True) o resultado é: {True and True}')
print(f'(True and False) o resultado é: {True and False}')
print(f'(False and True) o resultado é: {False and True}')
print(f'(False and False) o resultado é: {False and False}')

AND
(True and True) o resultado é: True
(True and False) o resultado é: False
(False and True) o resultado é: False
(False and False) o resultado é: False


In [ ]:
print('OR')
print(f'(True or True) o resultado é: {True or True}')
print(f'(True or False) o resultado é: {True or False}')
print(f'(False or True) o resultado é: {False or True}')
print(f'(False or False) o resultado é: {False or False}')

OR
(True or True) o resultado é: True
(True or False) o resultado é: True
(False or True) o resultado é: True
(False or False) o resultado é: False


In [ ]:
a, b , c = [], [], []

for lista in dados:
  if lista[1] <= 2000:
    a.append(lista)
  elif lista[1] > 2000 and lista[1] <= 2010:
    b.append(lista)
  else:
    c.append(lista)

In [ ]:
print(a)

[['Passat', 1991, False], ['Crossfox', 1990, False]]


In [ ]:
print(b)

[['Jetta Variant', 2003, False], ['Aston Martin DB4', 2006, False], ['Série 3 Cabrio', 2009, False]]


In [ ]:
print(c)

[['DS5', 2019, True], ['Palio Weekend', 2012, False], ['A5', 2019, True], ['Dodge Jorney', 2019, False], ['Carens', 2011, False]]


In [ ]:
a, b , c = [], [], []

for lista in dados:
  if lista[1] <= 2000:
    a.append(lista)
  elif 2000 < lista[1] <= 2010:
    b.append(lista)
  else:
    c.append(lista)

In [ ]:
print(a)

[['Passat', 1991, False], ['Crossfox', 1990, False]]


In [ ]:
print(b)

[['Jetta Variant', 2003, False], ['Aston Martin DB4', 2006, False], ['Série 3 Cabrio', 2009, False]]


In [ ]:
print(c)

[['DS5', 2019, True], ['Palio Weekend', 2012, False], ['A5', 2019, True], ['Dodge Jorney', 2019, False], ['Carens', 2011, False]]


# <font color=yellow> 10. Numpy Básico
---
Numpy é a abreviação de Numerical Python e é um dos pacotes mais importantes para processamento numérico em Python. Numpy oferece a base para a maioria dos pacotes de aplicações científicas que utilizem dados numéricos em Python (estruturas de dados e algoritmos). Pode-se destacar os seguintes recursos que o pacote Numpy contém:

- Um poderoso objeto array multidimensional;
- Funções matemáticas sofisticadas para operações com arrays sem a necessidade de utilização de laços *for*;
- Recursos de algebra linear e geração de números aleatórios

Além de seus óbvios usos científicos, o pacote NumPy também é muito utilizado em análise de dados como um eficiente contêiner multidimensional de dados genéricos para transporte entre diversos algoritmos e bibliotecas em Python.

**Versão:** 1.16.5

**Instalação:** https://scipy.org/install.html

**Documentação:** https://numpy.org/doc/1.16/

### Pacotes

Existem diversos pacotes Python disponíveis para download na internet. Cada pacote tem como objetivo a solução de determinado tipo de problema e para isso são desenvolvidos novos tipos, funções e métodos.

Alguns pacotes são bastante utilizados em um contexto de ciência de dados como por exemplo:

- Numpy
- Pandas
- Scikit-learn
- Matplotlib

Alguns pacotes não são distribuídos com a instalação default do Python. Neste caso devemos instalar os pacotes que necessitamos em nosso sistema para podermos utilizar suas funcionalidades.

# 10.1 Importando Todo o Pacote

### Padrão

In [ ]:
import numpy

In [ ]:
numpy.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Atribuindo um Apelido

In [ ]:
import numpy as np

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Importando um Pacote Específico

In [ ]:
from numpy import arange

In [ ]:
arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 10.2 Criando um Arrays Numpy

### A partir de Listas

In [ ]:
km = np.array([1000,2300,4987,1500])

In [ ]:
km

array([1000, 2300, 4987, 1500])

In [ ]:
type(km)

numpy.ndarray

In [ ]:
km.dtype

dtype('int64')

### A partir de Dados Externos

In [ ]:
km = np.loadtxt(fname = "carros-km.txt", dtype=int)

In [ ]:
km

array([ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
        99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
        46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
            0,      0,   5795,      0,  58848,  94381,  30163,  53332,
        17720,  33808,  90684,  43975,      0,      0,   5526,      0,
        93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
            0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
       119513,      0,      0,      0,      0,      0, 118895,  48509,
       100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
        54395,  26731,  44329, 118236, 113808,    610,      0,      0,
        12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
            0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
       110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
        26544,  52596,  47503,  89056,  28834, 110564,  56638,  17357,
      

In [ ]:
km.dtype

dtype('int64')

### Arrays com Duas Dimensões

In [ ]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]

In [ ]:
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [ ]:
acessorios = np.array(dados)

In [ ]:
acessorios

array([['Rodas de liga', 'Travas elétricas', 'Piloto automático',
        'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento',
        'Sensor crepuscular', 'Sensor de chuva'],
       ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4',
        'Painel digital', 'Piloto automático', 'Bancos de couro',
        'Câmera de estacionamento'],
       ['Piloto automático', 'Controle de estabilidade',
        'Sensor crepuscular', 'Freios ABS', 'Câmbio automático',
        'Bancos de couro', 'Central multimídia', 'Vidros elétricos']],
      dtype='<U24')

In [ ]:
km.shape

(258,)

In [ ]:
acesorios.shape

(3, 8)

### Comparando Desempenho com Listas

In [ ]:
np_array = np.arange(1000000)

In [ ]:
py_list = list(range(1000000))

In [ ]:
%time for _ in range(100): np_array *= 2

CPU times: user 76.3 ms, sys: 0 ns, total: 76.3 ms
Wall time: 79.5 ms


In [ ]:
%time for _ in range(100): py_list = [x * 2 for x in py_list]

CPU times: user 7.82 s, sys: 1.67 s, total: 9.49 s
Wall time: 9.52 s


# 10.3 Operações Aritméticas com Arrys Numpy

### Operações com Arrays e Constantes

In [ ]:
km = [44410., 5712., 37123., 0., 25757.]
anos = [2003, 1991, 1990, 2019, 2006]

In [ ]:
idade = 2020 - anos

TypeError: ignored

In [ ]:
km = np.array([44410., 5712., 37123., 0., 25757.])
anos = np.array([2003, 1991, 1990, 2019, 2006])

In [ ]:
idade = 2020 - anos

In [ ]:
idade

array([17, 29, 30,  1, 14])

### Operação entre Arrays

In [ ]:
km_media = km/idade

In [ ]:
km_media

array([2612.35294118,  196.96551724, 1237.43333333,    0.        ,
       1839.78571429])

### Operações com Arrays de Duas Dimensões

In [ ]:
dados = np.array([km, anos])

In [ ]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [ ]:
dados.shape

(2, 5)

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [ ]:
dados[0]

array([44410.,  5712., 37123.,     0., 25757.])

In [ ]:
dados[1]

array([2003., 1991., 1990., 2019., 2006.])

In [ ]:
km_media = dados[0]/(2020 - dados[1])

In [ ]:
km_media

array([2612.35294118,  196.96551724, 1237.43333333,    0.        ,
       1839.78571429])

# 10.4 Seleções com Arrays

In [ ]:
dados 

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

### Indexação

In [ ]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
contador[0]

0

In [ ]:
itens = 6
index = itens - 1
contador[index]

5

In [ ]:
contador[-1]

9

In [ ]:
dados[0]

array([44410.,  5712., 37123.,     0., 25757.])

In [ ]:
dados[1]

array([2003., 1991., 1990., 2019., 2006.])

In [ ]:
dados[1][2]

1990.0

In [ ]:
dados[1,2]

1990.0

### Fatiamento

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [ ]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
contador[1:4]

array([1, 2, 3])

In [ ]:
contador[1:8:2]

array([1, 3, 5, 7])

In [ ]:
contador[::2]

array([0, 2, 4, 6, 8])

In [ ]:
contador[1::2]

array([1, 3, 5, 7, 9])

In [ ]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [ ]:
dados[:, 1:4]

array([[ 5712., 37123.,     0.],
       [ 1991.,  1990.,  2019.]])

In [ ]:
dados[:, 1:3]

array([[ 5712., 37123.],
       [ 1991.,  1990.]])

In [ ]:
dados[:, 1:3][0] / (2020 - dados[:, 1:3][1])

array([ 196.96551724, 1237.43333333])

### Indexção com Arrays Booleano

In [ ]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
contador > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [ ]:
contador[contador > 5]

array([6, 7, 8, 9])

In [ ]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [ ]:
dados[1] > 2000

array([ True, False, False,  True,  True])

In [ ]:
dados[:, dados[1] > 2000]

array([[44410.,     0., 25757.],
       [ 2003.,  2019.,  2006.]])

In [ ]:
dados[:, dados[1] > 2000] / (2020 - dados[:, dados[1] > 2000][1])

array([[2612.35294118,    0.        , 1839.78571429],
       [ 117.82352941, 2019.        ,  143.28571429]])

# 10.5 Atributos e Métodos com Numpy

In [ ]:
dados = np.array([[44410., 5712., 37123., 0., 25757.],
                  [2003, 1991, 1990, 2019, 2006]])
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

## ndarray.shape

Retorna uma tupla com as dimensões do array.


In [ ]:
dados.shape

(2, 5)

## *ndarray.ndim*

Retorna o número de dimensões do array.

In [ ]:
dados.ndim

2

## *ndarray.size*

Retorna o número de elementos do array.

In [ ]:
dados.size

10

### *ndarray.dtype*

Retorna o tipo de dados dos elementos do array.

In [ ]:
dados.dtype

dtype('float64')

## *ndarray.T*

Retorna o array transposto, isto é, converte linhas em colunas e vice versa.

In [ ]:
dados.T

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

## *ndarray.tolist()*

Retorna o array como uma lista Python.

In [ ]:
dados.tolist()

[[44410.0, 5712.0, 37123.0, 0.0, 25757.0],
 [2003.0, 1991.0, 1990.0, 2019.0, 2006.0]]

## *ndarray.reshape(shape[, order])*

Retorna um array que contém os mesmos dados com uma nova forma.

In [ ]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
contador.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
contador.reshape((5,2), order='C')

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
contador.reshape((5,2), order='F')

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [ ]:
km = [44410, 5712, 37123, 0, 25757]
anos = [2003, 1991, 1990, 2019, 2006]

In [ ]:
info_carros = km + anos
info_carros

[44410, 5712, 37123, 0, 25757, 2003, 1991, 1990, 2019, 2006]

In [ ]:
np.array(info_carros)

array([44410,  5712, 37123,     0, 25757,  2003,  1991,  1990,  2019,
        2006])

In [ ]:
np.array(info_carros).reshape((2,5))

array([[44410,  5712, 37123,     0, 25757],
       [ 2003,  1991,  1990,  2019,  2006]])

In [ ]:
np.array(info_carros).reshape((5,2), order='F')

array([[44410,  2003],
       [ 5712,  1991],
       [37123,  1990],
       [    0,  2019],
       [25757,  2006]])

## *ndarray.resize(new_shape[, refcheck])*

Altera a forma e o tamanho do array.

In [ ]:
dados_new = dados.copy()
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [ ]:
dados_new.resize((3,5),refcheck=False)

In [ ]:
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.],
       [    0.,     0.,     0.,     0.,     0.]])

In [ ]:
dados_new[2] = dados_new[0] / (2021 - dados_new[1])

In [ ]:
dados_new

array([[44410.        ,  5712.        , 37123.        ,     0.        ,
        25757.        ],
       [ 2003.        ,  1991.        ,  1990.        ,  2019.        ,
         2006.        ],
       [ 2467.22222222,   190.4       ,  1197.51612903,     0.        ,
         1717.13333333]])

# 10.6 Estatísticas com Array Numpy

In [ ]:
anos = np.loadtxt(fname = "carros-anos.txt", dtype = int)
km = np.loadtxt(fname = "carros-km.txt")
valor = np.loadtxt(fname = "carros-valor.txt")

In [ ]:
anos.shape

(258,)

In [ ]:
dataset = np.column_stack((anos, km, valor))

In [ ]:
dataset

In [ ]:
dataset.shape

(258, 3)

## *np.mean()*

Retorna a média dos elementos do array ao longo do eixo especificado.

In [ ]:
np.mean(dataset, axis = 0)

array([ 2007.51162791, 44499.41472868, 98960.51310078])

In [ ]:
np.mean(dataset[:, 1])

44499.41472868217

In [ ]:
np.mean(dataset[:, 2])

98960.51310077519

## *np.std()*

Retorna o desvio padrão dos elementos do array ao longo do eixo especificado.

In [ ]:
np.std(dataset[:, 2])

29754.101150388564

## *ndarray.sum()*

Retorna a soma dos elementos do array ao longo do eixo especificado.

In [ ]:
dataset.sum(axis = 0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [ ]:
dataset[:, 1].sum()

11480849.0

In [ ]:
np.sum(dataset, axis = 0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [ ]:
np.sum(dataset[:, 2])

25531812.38

## *np.std()*

Retorna o desvio padrão dos elementos do array ao longo do eixo especificado.

In [ ]:
np.std(dataset[:, 2])

29754.101150388564

## *ndarray.sum()*

Retorna a soma dos elementos do array ao longo do eixo especificado.

In [ ]:
dataset.sum(axis = 0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [ ]:
dataset[:, 1].sum()

11480849.0

In [ ]:
np.sum(dataset, axis = 0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [ ]:
np.sum(dataset[:, 2])

25531812.38